#!/usr/bin/env python3
"""Throwaway helper to create the Slack / GitHub / Linear *bots* fabri needs for
a real repo run, run their OAuth flows, and write the resulting credentials into
a **gitignored** `.env.fabri.local` in the fabri repo root.

Design rules (this repo is PUBLIC):
  * The apps are created in each provider's browser console. Only the OAuth token
    exchange + env wiring is automated here.
  * Secrets are written ONLY to `.env.fabri.local` (matched by `.env*` in
    .gitignore) and `secrets/` (gitignored). The script refuses to write anywhere
    git does not ignore, so a secret can never be staged by accident.
  * Nothing secret is printed — values are masked in all output.
  * Stdlib only. No third-party deps, no crypto: the GitHub App flow uses the
    manifest + setup-URL redirect, so no JWT signing is needed at setup time.

Usage:
  python scripts/setup_bots.py all           # github, then slack, then linear
  python scripts/setup_bots.py github
  python scripts/setup_bots.py slack
  python scripts/setup_bots.py linear
  python scripts/setup_bots.py doctor        # show + live-check what's wired
  python scripts/setup_bots.py --self-test   # offline check of the safety plumbing

After a run:  source .env.fabri.local

Endpoints/scopes are current as of writing but providers move — each flow prints
the console URL it opens so you can eyeball scopes. Cross-check with:
  Slack   https://api.slack.com/authentication/oauth-v2
  GitHub  https://docs.github.com/apps/creating-github-apps/registering-a-github-app/registering-a-github-app-from-a-manifest
  Linear  https://developers.linear.app/docs/oauth/authentication
"""
from __future__ import annotations

import argparse
import http.server
import json
import os
import secrets as pysecrets
import stat
import subprocess
import sys
import threading
import urllib.parse
import urllib.request
import webbrowser
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / ".env.fabri.local"
SECRETS_DIR = REPO_ROOT / "secrets"
PEM_PATH = SECRETS_DIR / "github-app.pem"
CALLBACK_PORT = 8976
CALLBACK_BASE = f"http://localhost:{CALLBACK_PORT}"


# --------------------------------------------------------------------------- #
# safety plumbing
# --------------------------------------------------------------------------- #
def _mask(value: str) -> str:
    if not value:
        return "<empty>"
    if len(value) <= 8:
        return "****"
    return f"{value[:4]}…{value[-4:]} ({len(value)} chars)"


def _git_ignores(path: Path) -> bool:
    """True if git would ignore `path` (so a secret written here can't be staged)."""
    try:
        r = subprocess.run(
            ["git", "check-ignore", "-q", str(path)],
            cwd=REPO_ROOT,
            capture_output=True,
        )
        return r.returncode == 0
    except FileNotFoundError:
        return False


def _refuse_if_trackable(path: Path) -> None:
    if not _git_ignores(path):
        sys.exit(
            f"REFUSING to write secrets to {path} — git does not ignore it.\n"
            f"Add it to .gitignore first (this repo is public)."
        )


def _read_env() -> dict[str, str]:
    out: dict[str, str] = {}
    if not ENV_FILE.exists():
        return out
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):]
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip().strip("'\"")
    return out


def write_env(updates: dict[str, str]) -> None:
    """Merge `updates` into .env.fabri.local as `export KEY=VALUE`, chmod 600."""
    _refuse_if_trackable(ENV_FILE)
    merged = _read_env()
    merged.update({k: v for k, v in updates.items() if v is not None})
    header = (
        "# fabri bot credentials — LOCAL ONLY, gitignored. Do not commit.\n"
        "# Generated by scripts/setup_bots.py. `source` this file before a repo run.\n"
    )
    body = "".join(f"export {k}='{v}'\n" for k, v in sorted(merged.items()))
    ENV_FILE.write_text(header + body)
    ENV_FILE.chmod(0o600)
    print(f"  ✓ wrote {', '.join(sorted(updates))} → {ENV_FILE.name} (chmod 600)")


def _cred_var(provider: str, handle: str) -> str:
    """Mirror fabri.tools.credential_store.credential_env_var without importing it."""
    import re

    norm = lambda s: re.sub(r"[^A-Za-z0-9]", "_", s).upper()
    return f"FABRI_CRED_{norm(provider)}_{norm(handle)}"


# --------------------------------------------------------------------------- #
# one-shot OAuth callback capture
# --------------------------------------------------------------------------- #
def capture_redirect(path: str, *, open_url: str | None = None, serve_html: str | None = None) -> dict:
    """Serve a one-shot localhost endpoint, return the query params of the first
    request to `path`. Either open `open_url` in the browser, or serve `serve_html`
    at `/` (used for the GitHub manifest auto-submit form)."""
    captured: dict[str, str] = {}
    done = threading.Event()

    class Handler(http.server.BaseHTTPRequestHandler):
        def log_message(self, *_):  # silence
            pass

        def do_GET(self):
            parsed = urllib.parse.urlparse(self.path)
            if serve_html and parsed.path == "/":
                self.send_response(200)
                self.send_header("Content-Type", "text/html")
                self.end_headers()
                self.wfile.write(serve_html.encode())
                return
            if parsed.path == path:
                captured.update(
                    {k: v[0] for k, v in urllib.parse.parse_qs(parsed.query).items()}
                )
                self.send_response(200)
                self.send_header("Content-Type", "text/html")
                self.end_headers()
                self.wfile.write(
                    b"<h2>fabri: captured. You can close this tab.</h2>"
                )
                done.set()
                return
            self.send_response(404)
            self.end_headers()

    srv = http.server.HTTPServer(("localhost", CALLBACK_PORT), Handler)
    t = threading.Thread(target=srv.serve_forever, daemon=True)
    t.start()
    try:
        target = open_url or CALLBACK_BASE + "/"
        print(f"  → opening browser: {target.split('?')[0]} …")
        if not webbrowser.open(target):
            print(f"    (couldn't auto-open; paste this into a browser)\n    {target}")
        if not done.wait(timeout=300):
            sys.exit("  ✗ timed out waiting for the browser redirect (5 min).")
    finally:
        srv.shutdown()
    return captured


def _http_json(method: str, url: str, *, data=None, headers=None) -> dict:
    body = None
    hdrs = {"Accept": "application/json", "User-Agent": "fabri-setup-bots"}
    if headers:
        hdrs.update(headers)
    if data is not None:
        if isinstance(data, dict):
            body = urllib.parse.urlencode(data).encode()
            hdrs.setdefault("Content-Type", "application/x-www-form-urlencoded")
        else:
            body = data
    req = urllib.request.Request(url, data=body, method=method, headers=hdrs)
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode())


# --------------------------------------------------------------------------- #
# GitHub App (bot) — manifest + setup-URL flow (fully automated, no JWT)
# --------------------------------------------------------------------------- #
def setup_github() -> None:
    print("\n== GitHub App (bot) ==")
    print("  (creating the App is repo-agnostic — you pick the repo in the browser at")
    print("   the Install step. The prompt below is optional and only saves a default")
    print("   target repo for the later `fabri repo run`.)")
    repo = input("  default repo for runs (owner/name) [skip]: ").strip()
    app_name = input(f"  app name [fabri-run-bot-{pysecrets.token_hex(2)}]: ").strip() \
        or f"fabri-run-bot-{pysecrets.token_hex(2)}"
    # public=True → app gets a github.com/apps/<slug> page ANYONE can install
    # (the Vercel model). private → only you can install it (fine for first proof).
    public = input("  make it PUBLIC so anyone can install it (Vercel-style)? [y/N]: ").strip().lower() == "y"
    state = pysecrets.token_urlsafe(16)

    manifest = {
        "name": app_name,
        "url": "https://github.com/Rushour0/fabri",
        "redirect_url": f"{CALLBACK_BASE}/callback/github",
        "setup_url": f"{CALLBACK_BASE}/callback/github-setup",
        "setup_on_update": True,
        "public": public,
        "default_permissions": {
            "contents": "write",
            "pull_requests": "write",
            "issues": "write",
            "metadata": "read",
        },
        "default_events": [],
    }
    # GitHub requires the manifest submitted as a POST form. Auto-submit it.
    form = f"""<!doctype html><body onload="document.forms[0].submit()">
      <p>Creating the GitHub App… if nothing happens, click the button.</p>
      <form method="post" action="https://github.com/settings/apps/new?state={state}">
        <input type="hidden" name="manifest" value='{json.dumps(manifest).replace("'", "&#39;")}'>
        <button type="submit">Create GitHub App</button>
      </form></body>"""
    got = capture_redirect("/callback/github", serve_html=form)
    code = got.get("code")
    if not code:
        sys.exit("  ✗ no manifest code returned.")

    conv = _http_json(
        "POST", f"https://api.github.com/app-manifests/{code}/conversions",
        headers={"Accept": "application/vnd.github+json"},
    )
    app_id = str(conv["id"])
    SECRETS_DIR.mkdir(exist_ok=True)
    _refuse_if_trackable(PEM_PATH)
    PEM_PATH.write_text(conv["pem"])
    PEM_PATH.chmod(0o600)
    print(f"  ✓ app '{app_name}' created (id {app_id}); PEM → secrets/{PEM_PATH.name}")

    # Install on the repo; the setup_url redirect carries installation_id.
    install_url = f"{conv['html_url']}/installations/new"
    print("  → now INSTALL the app on your repo (select just the one repo).")
    inst = capture_redirect("/callback/github-setup", open_url=install_url)
    installation_id = inst.get("installation_id", "")

    env_updates = {
        _cred_var("github", "app_id"): app_id,
        _cred_var("github", "installation_id"): installation_id,
        _cred_var("github", "private_key"): str(PEM_PATH),
        "GITHUB_APP_CLIENT_ID": conv.get("client_id", ""),
        "GITHUB_APP_CLIENT_SECRET": conv.get("client_secret", ""),
        "GITHUB_APP_WEBHOOK_SECRET": conv.get("webhook_secret") or "",
    }
    if repo:
        env_updates["FABRI_REPO"] = repo
    write_env(env_updates)
    print(f"  installation_id: {_mask(installation_id)}")


# --------------------------------------------------------------------------- #
# Slack bot + OAuth v2
# --------------------------------------------------------------------------- #
SLACK_MANIFEST = {
    "display_information": {"name": "fabri-run-bot"},
    "features": {"bot_user": {"display_name": "fabri", "always_online": True}},
    "oauth_config": {
        "redirect_urls": [f"{CALLBACK_BASE}/callback/slack"],
        "scopes": {"bot": ["chat:write", "channels:read"]},
    },
    "settings": {"org_deploy_enabled": False, "socket_mode_enabled": False},
}


def slack_manifest(public_base: str | None) -> dict:
    if public_base is None:
        return SLACK_MANIFEST

    from fabri.service.slack_oauth import SLACK_BOT_SCOPES

    base = public_base.rstrip("/")
    return {
        "display_information": dict(SLACK_MANIFEST["display_information"]),
        "features": {"bot_user": dict(SLACK_MANIFEST["features"]["bot_user"])},
        "oauth_config": {
            "redirect_urls": [f"{base}/slack/oauth/callback"],
            "scopes": {"bot": SLACK_BOT_SCOPES.split(",")},
        },
        "settings": {
            "event_subscriptions": {
                "request_url": f"{base}/slack/events",
                "bot_events": [
                    "app_mention",
                    "message.channels",
                    "app_uninstalled",
                    "tokens_revoked",
                ],
            },
            "org_deploy_enabled": False,
            "socket_mode_enabled": False,
        },
    }


def setup_slack(public: bool = False) -> None:
    if not public:
        print("\n== Slack bot ==")
        print("  1) Create the app from a manifest: https://api.slack.com/apps?new_app=1")
        print("     → 'From a manifest' → your workspace → paste the JSON below:")
        print("     " + json.dumps(SLACK_MANIFEST))
        print("  2) On the app's 'Basic Information' page copy these:")
        client_id = input("     Client ID: ").strip()
        client_secret = input("     Client Secret: ").strip()
        signing_secret = input("     Signing Secret (for inbound events): ").strip()

        authorize = "https://slack.com/oauth/v2/authorize?" + urllib.parse.urlencode({
            "client_id": client_id,
            "scope": "chat:write,channels:read",
            "redirect_uri": f"{CALLBACK_BASE}/callback/slack",
            "state": pysecrets.token_urlsafe(12),
        })
        got = capture_redirect("/callback/slack", open_url=authorize)
        code = got.get("code")
        if not code:
            sys.exit("  ✗ no OAuth code returned.")
        tok = _http_json("POST", "https://slack.com/api/oauth.v2.access", data={
            "client_id": client_id,
            "client_secret": client_secret,
            "code": code,
            "redirect_uri": f"{CALLBACK_BASE}/callback/slack",
        })
        if not tok.get("ok"):
            sys.exit(f"  ✗ Slack token exchange failed: {tok.get('error')}")
        bot_token = tok["access_token"]
        print(f"  ✓ bot token: {_mask(bot_token)} (team {tok.get('team', {}).get('name')})")

        channel = input("  channel id to post in (e.g. C0123ABCD): ").strip()
        write_env({
            _cred_var("slack", "default"): bot_token,
            "SLACK_BOT_TOKEN": bot_token,      # fabri config compat (slack_notify)
            "SLACK_SIGNING_SECRET": signing_secret,
            "FABRI_SLACK_CHANNEL": channel,
        })
        return

    from fabri.service.slack_oauth import SLACK_BOT_SCOPES

    public_base = os.environ.get("FABRI_PUBLIC_BASE_URL") or input(
        "  Public HTTPS base URL (e.g. https://fabri.example.com): "
    ).strip()
    if not public_base.startswith("https"):
        print("  ⚠ public base URL should start with https")
    base = public_base.rstrip("/")

    print("\n== Slack public/distributable app ==")
    print("  Paste this JSON in the Slack app manifest editor:")
    print(json.dumps(slack_manifest(public_base)))
    print("  On the app's 'Basic Information' page copy these:")
    client_id = input("     Client ID: ").strip()
    client_secret = input("     Client Secret: ").strip()
    signing_secret = input("     Signing Secret (for inbound events): ").strip()

    write_env({
        "SLACK_CLIENT_ID": client_id,
        "SLACK_CLIENT_SECRET": client_secret,
        "SLACK_SIGNING_SECRET": signing_secret,
        "FABRI_PUBLIC_BASE_URL": public_base,
    })

    authorize = "https://slack.com/oauth/v2/authorize?" + urllib.parse.urlencode({
        "client_id": client_id,
        "scope": SLACK_BOT_SCOPES,
        "redirect_uri": f"{base}/slack/oauth/callback",
    })
    print(f"  Install URL: {base}/slack/install")
    print(f"  Authorize URL (reference only; use the install URL for signed state): {authorize}")
    print("  (1) api.slack.com → Manage Distribution → Activate Public Distribution.")
    print(f"  (2) OAuth & Permissions → Redirect URLs → add {base}/slack/oauth/callback.")
    print(f"  (3) Event Subscriptions → Request URL {base}/slack/events + subscribe to the bot events.")
    print(
        "  (4) Set FABRI_PUBLIC_BASE_URL, SLACK_CLIENT_ID, SLACK_CLIENT_SECRET, "
        "SLACK_SIGNING_SECRET, then restart `fabri serve`."
    )
    print(
        "  (5) PERSISTENCE: the install DB is at <home-root>/installs.db — it MUST be on "
        "a persistent volume, or every redeploy logs out all workspaces."
    )


# --------------------------------------------------------------------------- #
# Linear OAuth (actor=application → posts as the bot)
# --------------------------------------------------------------------------- #
def setup_linear() -> None:
    print("\n== Linear OAuth app ==")
    print("  1) Create an OAuth application:")
    print("     https://linear.app/settings/api/applications/new")
    print(f"     Set the redirect URI to exactly: {CALLBACK_BASE}/callback/linear")
    client_id = input("  Client ID: ").strip()
    client_secret = input("  Client Secret: ").strip()

    authorize = "https://linear.app/oauth/authorize?" + urllib.parse.urlencode({
        "client_id": client_id,
        "redirect_uri": f"{CALLBACK_BASE}/callback/linear",
        "response_type": "code",
        "scope": "read,write",
        "state": pysecrets.token_urlsafe(12),
        "actor": "application",   # PRs/comments attributed to the bot, not you
    })
    got = capture_redirect("/callback/linear", open_url=authorize)
    code = got.get("code")
    if not code:
        sys.exit("  ✗ no OAuth code returned.")
    tok = _http_json("POST", "https://api.linear.app/oauth/token", data={
        "client_id": client_id,
        "client_secret": client_secret,
        "code": code,
        "redirect_uri": f"{CALLBACK_BASE}/callback/linear",
        "grant_type": "authorization_code",
    })
    access = tok.get("access_token")
    if not access:
        sys.exit(f"  ✗ Linear token exchange failed: {tok}")
    print(f"  ✓ access token: {_mask(access)}")
    write_env({_cred_var("linear", "default"): access})


# --------------------------------------------------------------------------- #
# doctor — show + live-check
# --------------------------------------------------------------------------- #
def doctor() -> None:
    print("\n== doctor ==")
    env = _read_env()
    if not env:
        print("  no .env.fabri.local yet — run: python scripts/setup_bots.py all")
        return
    for k, v in sorted(env.items()):
        print(f"  {k} = {_mask(v)}")

    # live checks that need no crypto
    slack = env.get("SLACK_BOT_TOKEN")
    if slack:
        try:
            r = _http_json("POST", "https://slack.com/api/auth.test",
                           headers={"Authorization": f"Bearer {slack}"})
            print(f"  slack auth.test: {'ok as ' + r.get('user', '?') if r.get('ok') else r.get('error')}")
        except Exception as e:  # noqa: BLE001
            print(f"  slack auth.test: error {e}")
    linear = env.get(_cred_var("linear", "default"))
    if linear:
        try:
            r = _http_json("POST", "https://api.linear.app/graphql",
                           data=json.dumps({"query": "{ viewer { name } }"}).encode(),
                           headers={"Authorization": linear, "Content-Type": "application/json"})
            name = r.get("data", {}).get("viewer", {}).get("name")
            print(f"  linear viewer: {name or r}")
        except Exception as e:  # noqa: BLE001
            print(f"  linear viewer: error {e}")
    print("  github App token needs JWT signing — validated by the repo-run harness, not here.")


def _self_test() -> None:
    """Offline check of the safety plumbing (no network, no browser)."""
    assert _cred_var("slack", "acme-eng") == "FABRI_CRED_SLACK_ACME_ENG"
    assert _cred_var("github", "app_id") == "FABRI_CRED_GITHUB_APP_ID"
    assert _git_ignores(ENV_FILE), ".env.fabri.local must be gitignored"
    assert _git_ignores(PEM_PATH), "secrets/ must be gitignored"
    assert not _git_ignores(REPO_ROOT / "README.md"), "sanity: README is tracked"
    print("self-test OK: cred names correct; .env.fabri.local + secrets/ are gitignored.")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("target", nargs="?", choices=["all", "github", "slack", "linear", "doctor"])
    p.add_argument("--self-test", action="store_true", help="offline safety-plumbing check")
    p.add_argument("--public", action="store_true", help="set up Slack for public/distributable multi-workspace install (OAuth-per-workspace) instead of single-tenant localhost")
    args = p.parse_args()

    if args.self_test:
        _self_test()
        return
    if not args.target:
        p.print_help()
        return

    steps = {"github": setup_github, "slack": setup_slack, "linear": setup_linear}
    if args.target == "doctor":
        doctor()
    elif args.target == "all":
        for name, fn in steps.items():
            if name == "slack":
                setup_slack(public=False)
            else:
                fn()
        print("\nAll done. Next:  source .env.fabri.local  &&  python scripts/setup_bots.py doctor")
    elif args.target == "slack":
        setup_slack(public=args.public)
        print(f"\nDone. Next:  source .env.fabri.local  &&  python scripts/setup_bots.py doctor")
    else:
        steps[args.target]()
        print(f"\nDone. Next:  source .env.fabri.local  &&  python scripts/setup_bots.py doctor")


if __name__ == "__main__":
    main()
